server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  #配置读写分离sharding-JDBC
  shardingsphere:
    datasource:
      names:
        master,slave
      #主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:  jdbc:mysql://192.168.201.100:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Weizijierhuo0214
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.201.101:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Weizijierhuo0214
    masterslave:
      #读写分离配置
      load-balance-algorithm-type: round_robin #轮询策略
      #最终的数据源名称
      name: dataSource
      #主库数据源名称
      master-data-source-name: master
      #从库数据源名称列表
      slave-data-source-names: slave
    props:
      sql:
        show: true  #开启sql显示
  main: #允许bean定义覆盖
    allow-bean-definition-overriding: true
  #Redis相关配置
  redis:
    host: 192.168.201.100
    port: 6379
    #password: 123456
    database: 0 #操作0号数据库
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /usr/local/Project_Practice/reggie/reggie_take_out/pic/
  #E:\\Project Practice\reggie\reggie_take_out\pic\

